import Head from 'next/head';
import HomeTemplate from '@/components/template/HomeTemplate';
import { ProjectItemType } from '@/constants/types';
import { useEffect, useState } from 'react';
import { ProjectRepository } from '@/apis/project';

// TODO 서버 사이드 애러 핸들링
// export const getServerSideProps = async () => {
//  try {
//    const [popRes, latRes] = await Promise.all([
//      ProjectRepository.getMainProjectListAsync('POPULAR'),
//      ProjectRepository.getMainProjectListAsync('LATEST'),
//    ]);
//    const data = {
//      popularProjects: popRes.data.projectList,
//      latestProjects: latRes.data.projectList,
//    };
//    return { props: data };
//  } catch (error) {
//    return { props: { ...(error as ApiError) } };
//  }
// };

const Home = () => {
  const [popularProjects, setPopularProjects] = useState<ProjectItemType[]>([]);
  const [latestProjects, setLatestProjects] = useState<ProjectItemType[]>([]);

  useEffect(() => {
    const getMainData = async () => {
      const [popRes, latRes] = await Promise.all([
        ProjectRepository.getMainProjectListAsync('POPULAR'),
        ProjectRepository.getMainProjectListAsync('LATEST'),
      ]);
      setPopularProjects(popRes.data.projectList);
      setLatestProjects(latRes.data.projectList);
    };
    getMainData();
  }, []);

  return (
    <>
      <Head>
        <title>안녕, 푸르름</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {popularProjects && latestProjects && (
        <HomeTemplate
          popularProjects={popularProjects}
          newProjects={latestProjects}
        />
      )}
    </>
  );
};
export default Home;
