import Head from 'next/head';

import useModal from '@/hooks/useModal';
import ModalTemplate from '@/components/common/ModalTemplate';
import Button from '@/components/common/Button';

const Home = () => {
  const { openModal } = useModal();

  const handleModalOpen = () => {
    openModal(
      <ModalTemplate title="test Modal">
        <p>testModal</p>
      </ModalTemplate>,
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Get started by editing</p>
          <Button onClick={handleModalOpen}>test Modal</Button>
        </div>
      </main>
    </>
  );
};

export default Home;
